[project]
name = "qpi"
description = "qpi-tool"
version = "1.1.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = [
    ".", "src", "tests"
]
